import { NativeModules } from 'react-native';
import type { BankAccountFormView } from '../types';

const { BankAccountFormFunctions } = NativeModules;

/**
 * Validates the bank account form inputs.
 * @return {Promise<boolean>} - A promise that resolves with a boolean indicating whether the inputs are valid or not.
 */
export async function validate(): Promise<boolean> {
  return new Promise(resolve => {
    BankAccountFormFunctions.validate((isValid: boolean) => {
      resolve(isValid);
    });
  });
}

/**
 * Tokenizes the bank account form inputs.
 * @return {Promise<BankAccountFormView.Token>} - A promise that resolves with the token generated by the bank account form.
 */
export async function tokenize(): Promise<BankAccountFormView.Token> {
  return new Promise(resolve => {
    BankAccountFormFunctions.tokenize((token: BankAccountFormView.Token) => {
      resolve(token);
    });
  });
}
