"use strict";

/**
 * Validates the bank account form inputs.
 * @return {Promise<boolean>} - A promise that resolves with a boolean indicating whether the inputs are valid or not.
 */
async function validate() {
  return new Promise(resolve => {
    BankAccountFormFunctions.validate((isValid) => {
      resolve(isValid);
    });
  });
}

/**
 * Tokenizes the bank account form inputs.
 * @return {Promise<string>} - A promise that resolves with the token generated by the bank account form.
 */
async function tokenize() {
  return new Promise(resolve => {
    BankAccountFormFunctions.tokenize((token) => {
      resolve(token);
    });
  });
}

module.exports = {
  validate,
  tokenize,
};
